export const REDIS_TOKEN_BUCKET_SCRIPT = [
    "-- Veil coordinator token bucket",
    "-- KEYS[1] = bucket key",
    "-- ARGV[1] = now_ms",
    "-- ARGV[2] = refill_rate_per_second",
    "-- ARGV[3] = capacity",
    "-- ARGV[4] = cost",
    "-- ARGV[5] = ttl_ms",
    "",
    "local bucket_key = KEYS[1]",
    "local now_ms = tonumber(ARGV[1])",
    "local refill_rate_per_second = tonumber(ARGV[2])",
    "local capacity = tonumber(ARGV[3])",
    "local cost = tonumber(ARGV[4])",
    "local ttl_ms = tonumber(ARGV[5])",
    "",
    "local state = redis.call('HMGET', bucket_key, 'available_tokens', 'refilled_at_ms')",
    "local available_tokens = tonumber(state[1])",
    "local refilled_at_ms = tonumber(state[2])",
    "",
    "if available_tokens == nil or refilled_at_ms == nil then",
    "  available_tokens = capacity",
    "  refilled_at_ms = now_ms",
    "end",
    "",
    "local elapsed_ms = math.max(0, now_ms - refilled_at_ms)",
    "local replenished_tokens = (elapsed_ms / 1000) * refill_rate_per_second",
    "available_tokens = math.min(capacity, available_tokens + replenished_tokens)",
    "",
    "local allowed = 0",
    "local retry_after_ms = 0",
    "",
    "if available_tokens >= cost then",
    "  available_tokens = available_tokens - cost",
    "  allowed = 1",
    "else",
    "  local missing_tokens = cost - available_tokens",
    "  if refill_rate_per_second > 0 then",
    "    retry_after_ms = math.ceil((missing_tokens / refill_rate_per_second) * 1000)",
    "  else",
    "    retry_after_ms = 60000",
    "  end",
    "end",
    "",
    "redis.call('HSET', bucket_key, 'available_tokens', available_tokens, 'refilled_at_ms', now_ms)",
    "redis.call('PEXPIRE', bucket_key, ttl_ms)",
    "",
    "return {allowed, math.floor(available_tokens), math.ceil(retry_after_ms / 1000)}",
].join("\n");
